apiVersion: v1
kind: Service
metadata:
  name: weatherapi-srv
spec:
  type: NodePort
  selector:
    app: weatherapiservice
  ports:
    - name: weatherapiservice
      protocol: TCP
      port: 8080
      targetPort: 8080