name: Deploy to Minikube using GitHub Actions

on:
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
      with:
        repository: alvinyanson/CICD.NetWebAPI
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Build minikube image
      run: |
        minikube image build -t ayansonarcanys/weatherapiservice:latest . 
    - name: Build docker image
      run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t ayansonarcanys/weatherapiservice:latest .
          echo -n "verifying images:"
          docker images
    - name: List files
      run: |
        ls -la
    - name: List Change directory
      run: |
        ls -la
        cd ..
        ls -R
    - name: Deploy to minikube
      run: |
        kubectl apply -f ./webapi.yaml
        kubectl get pod -l app=weatherapiservice
        timeout $((300+5)) kubectl wait --for=condition=ready pod -l app=weatherapiservice --timeout=300s
    - name: Test service URLs
      run: |
        minikube service list
        minikube service weatherapi-srv --url
        echo "------------------opening the service------------------"
        curl $(minikube service weatherapi-srv --url)      
