name: Deploy to Docker Desktop using GitHub Actions

on:
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build example and deploy to Docker Desktop
    steps:
    - uses: actions/checkout@v4
      with:
        repository: alvinyanson/CICD.NetWebAPI
    - name: Set up Docker Buildx
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use
    - name: Build Docker image
      run: | 
          docker build -f ./Dockerfile -t ayansonarcanys/weatherapiservice:latest .
          echo -n "Verifying images:"
          docker images
    - name: Deploy to Docker Desktop
      run: |
        docker run -d --name weatherapi -p 8080:8080 ayansonarcanys/weatherapiservice:latest
    - name: Test service URLs
      run: |
        echo "------------------opening the service------------------"
        curl http://localhost:8080/WeatherForecast
